### ISSUE TITLE
支持label和value的区分

### ISSUE THREAD

**Issue by shepherdwind** [react-component/select#10]
正常的select应该是这样的：

```
[
   { value: 'one', label: 'One' },
   { value: 'two', label: 'Two' }
]
```

选择one的时候，input显示的是One，显示的是label的值。value是one，两个还是不一样的。现在select展示的就是value的值。

https://github.com/JedWatson/react-select 这个select就是这种符合原生select模式的。

**Comment by shepherdwind** [comment]
测试代码：

把examples/single.js里面的改成如下：

```
   <Option value="lucy">lucy 1</Option>
        <Option value="disabled" disabled>disabled</Option>
        <Option value="yiminghe">yiminghe 1</Option>
```

这时候下拉框线上的是lucy 1，选中后input的值应该也是lucy 1，但实际结果是lucy。

**Comment by xujihui1985** [comment]
![image](https://cloud.githubusercontent.com/assets/1619030/8246513/3b9f1776-1672-11e5-9624-352ab4cdf4c0.png)

+1 还有这个场景，Options中显示的是html, 我希望选中后，显示的displayname, 但实际取value的时候能取到domainname
