### ISSUE TITLE
单选模式下，关闭 dropdown时， 希望能触发一次 onSearch

### ISSUE THREAD

**Issue by eternalsky** [react-component/select#100]
https://github.com/react-component/select/blob/master/src/Select.jsx#L479

目的是为了让搜索的结果可以回到原位，触发一次 onSearch

**Comment by Gavinchen92** [comment]
如果不希望触发怎么办, 有办法关闭吗

**Comment by yesmeck** [comment]
忽略 value 为空的回调。

**Comment by Gavinchen92** [comment]
@yesmeck 那真的为空的情况也被忽略了

**Comment by yesmeck** [comment]
嗯，暂时想不到比较优雅的方法同时兼容两种情况。

**Comment by Gavinchen92** [comment]
@yesmeck 不能加个onDropMenuClosed 之类的钩子兼容楼主的情况吗，　关闭必定会触发onSearch感觉不太灵活

**Comment by yesmeck** [comment]
嗯，感觉原来的需求在  `onSelect` 的时候来清空搜索可能更好点，但是现在再改的话会造成不兼容。

**Comment by Gavinchen92** [comment]
@yesmeck 
说一下为什么我们现在业务中有这个需求
现我们业务中有一些下拉选框因为数据量过大所以要设置成可检索, 后台进行模糊匹配, 返回下拉框的数据
根据字面意思我们需要的是Autocomplete这个组件, 但是AutoComplete是可自行输入或可选中, 我们需要的是用户只能选择下拉框的内容, 实际上我们需要的是id, 这样的只有Select符合需求
 刚开始用的时候我们因为我们只需要id, 所以没有设置labelInValue=true, 这样的话会导致收回Dropdown触发的onSearch事件因为查询出来的值与Select选中的值不匹配, 所以输入框中不显示label, 而显示key的问题,
现在设置了labelInValue倒是解决了这个问题, 不过我觉得这个不是很完美, 不知道你们内部能不能考虑一下Autocomplete添加一个类似Select这样的模式, 还有就是可以增加一个loading属性, loading放置在dropdown上面, 这样既可以显示正在查询, 也可以防止用户在查询时点击Option

**Comment by Gavinchen92** [comment]
@yesmeck  lz的这个需求其实是合理的, 只不过和我们现在的不太符合

**Comment by yesmeck** [comment]
> Autocomplete添加一个类似Select这样的模式

那不就是搜索模式么。

> 还有就是可以增加一个loading属性, loading放置在dropdown上面, 这样既可以显示正在查询, 也可以防止用户在查询时点击Option

这个可以考虑。

**Comment by afc163** [comment]
loading 可以用 notFoundContent 来实现。

**Comment by Gavinchen92** [comment]
@yesmeck 搜索模式关闭时会触发一次onSearch所以不太好

**Comment by Gavinchen92** [comment]
@afc163  如果使用 `notFoundContent: loading ? <Spin  size="small" />`  : 'not found', 的话只会在第一次查询的时候触发, 所以查询时我们同时把children设为undefined, 也可以达到想要的效果
