### ISSUE TITLE
使用正则进行过滤

### ISSUE THREAD

**Issue by eternalsky** [react-component/select#105]
https://github.com/react-component/select/blob/8f0123ce53ca158801ea20d11f545e86fcdc93da/src/Select.jsx#L22

目前使用字符串的 indexOf 来执行的，如果使用正则的话，还可以提供出忽略大小写的配置

**Comment by benjycui** [comment]
使用 `filterOption` 即可。

**Comment by eternalsky** [comment]
恩，没注意 filter Option 还可以是个函数
