### ISSUE TITLE
react 15.2.1 出现警告

### ISSUE THREAD

**Issue by lovesmilesha** [react-component/select#109]
warning.js:44 Warning: Unknown props `tag`, `hiddenClassName`, `visible` on <ul> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop

**Comment by lovesmilesha** [comment]
问题定位是由于SelectTrigger组件选择导致的

**Comment by yiminghe** [comment]
重装，升级到最新

**Comment by lovesmilesha** [comment]
版本更新的很快啊，给力！
