### ISSUE TITLE
Searching with both lowercase and uppcase text

### ISSUE THREAD

**Issue by michelemendel** [react-component/select#117]
It doesn't seem possible to use both uppercase and lowercase when searching.

**Comment by benjycui** [comment]
https://github.com/react-component/select#select-props

`filterOption`

**Comment by michelemendel** [comment]
I was looking at this, but it's not clear how to use it. Do you need to write a function that returns a boolean for the search, and what is the option parameter for? The examples are not clear on to use it either.

**Comment by michelemendel** [comment]
Ok, I solved with a function tests option.key against the input value.
