### ISSUE TITLE
输入中文时会多次触发 onSearch

### ISSUE THREAD

**Issue by afc163** [react-component/select#123]
<img width="85" alt="image" src="https://cloud.githubusercontent.com/assets/507615/19598574/2410e7c2-97ce-11e6-9bc2-2f0dbaae3fd1.png">

**Comment by xujihui1985** [comment]
是输入法的时候吗？ 可以用这个 onCompositionEnd onCompositionStart onCompositionUpdate

**Comment by afc163** [comment]
Select 组件的 input 是内建的，外部不好处理。

**Comment by xujihui1985** [comment]
恩，只能在select这个组件处理这几个事件，最好所有的input组件都能处理这个事件，输入法的时候不触发onchange事件

**Comment by yesmeck** [comment]
https://github.com/facebook/react/issues/3926

**Comment by xujihui1985** [comment]
这个还不太好改，试了下改rc-select, 一旦用了composition event,  就不能当做控制组件使用，而且chrome和ff下行为还不太一样

**Comment by tofdragon** [comment]
这个问题是输入法的问题,IE中是不会的,google输入法会存在

**Comment by Gavinchen92** [comment]
为什么选中一个Option时也会触发一次onSearch, 且value为空字符串
