### ISSUE TITLE
在Modal上再弹出一个Modal时，有时候新弹出的Modal反而在下面一层

### ISSUE THREAD

**Issue by ptlinyi** [react-component/select#128]
用的都是<Modal>的方式，通过设置visible来进行弹框，但有时候新弹出的反而在下面一层，有时候又正常，随机的，这是BUG呢，还是有哪里需要注意的吗？

**Comment by ptlinyi** [comment]
已解决。

**Comment by fritx** [comment]
@ptlinyi 请问咋解决~ 我这边也是在ant-design的`<Modal>`中，展示了`<Select>`和`<TreeSelect>`，
然后Modal内容较长，可上下滚动，但滚动时，Dropdown会卡在同一个位置
