### ISSUE TITLE
Case insensitive "search/filter"

### ISSUE THREAD

**Issue by behind-design** [react-component/select#132]
First of all thank u for the work on this component, is awesome and it's perfect for a project I'm currently working on.

Nonetheless, I have to implement a case insensitive "search/filter" for the component. And going over the documentation I couldn't find anything related to it.

I probably should tell u that we're using it with the "tags" options, so we can list a bunch of specialties, that we then send to an API.

I would appreciate whatever help you can give.

Thanks!

**Comment by benjycui** [comment]
Tried `filterOption`?
