### ISSUE TITLE
自定义Select中选择后回填到Select中的render

### ISSUE THREAD

**Issue by cosyman** [react-component/select#138]
optionLabelProp 可以是value或children，  value通常是ID，children可能会定义的比较复杂（头像什么的）。在选中后希望在输入框中只显示选中项的名称。  不知道该如何做，或者提供optionLabel的自定义？

**Comment by afc163** [comment]
`optionLabelProp="xxxxxxx"`


```
<Option xxxxxxx={<div>what ever you want put in Select</div>}></Option>
```

**Comment by cosyman** [comment]
@afc163   可以使用了😄
