### ISSUE TITLE
placeholder

### ISSUE THREAD

**Issue by Grifree** [react-component/select#139]
[help] 默认值value="", 没有值时,value是空字符串,但好像空字符串,组件也当做一个值了..因为此时placeholder设置了,却不显示.. 请问我该如何处理

**Comment by benjycui** [comment]
设为 `null` 可好？

**Comment by Grifree** [comment]
试过了 不行呢 , 只有value是array时,即是是空数组,也会有placeholder

**Comment by afc163** [comment]
`value={undefined}`

**Comment by Grifree** [comment]
可以了 , 谢谢大牛们(￣▽￣)~*

**Comment by benjycui** [comment]
感觉还是得修复一下。

**Comment by benjycui** [comment]
Close in: https://github.com/react-component/select/pull/135
