### ISSUE TITLE
同一个页面两个select,option的数据是一样的,出现data-reactid重复

### ISSUE THREAD

**Issue by Grifree** [react-component/select#143]
![image](https://cloud.githubusercontent.com/assets/14190298/20820815/eb301c2c-b878-11e6-8914-af58e5737736.png)
而且我必须保留两个select,请问怎么解决这问题呢 @luolonghao

**Comment by benjycui** [comment]
`<Option>` value 一样是没意义啊，value 要唯一。

**Comment by Grifree** [comment]
每个select的Option虽然是一样的 ,但是value是不一样的呢,不过两个value是数组,数组中有重复的元素

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by yesmeck** [comment]
没回复先关闭了。
