### ISSUE TITLE
Doesn't scroll with keyboard arrows

### ISSUE THREAD

**Issue by behind-design** [react-component/select#147]
Hi there @yiminghe, I'm having this weird problem where I cannot scroll inside the list of items with the keyboard arrows. And I was wondering if u would have any idea why that might be.

This is the code for the render method I'm using:

```javascript
<Select
    value={selected}
    tags
    ref={r => this.select = r}
    placeholder={`${contents.placeholder_refer}...`}
    animation={null}
    choiceTransitionName={null}
    dropdownMenuStyle={{ maxHeight: 200 }}
    optionFilterProp="children"
    optionLabelProp="children"
    style={{ width: '100%', position: 'absolute', left: 0, bottom: 0 }}
    onSelect={this.onSelect}
    onDeselect={this.onDeselect}
    getPopupContainer={getDropdownContainer}
    filterOption={(input, child) => lower(child.props.name).indexOf(lower(input))}
    tokenSeparators={[' ', ',']}>
        { map(all_specialties, (spec, name, i) => <Option key={spec} value={spec.id} name={name}>{ name }</Option>) }
</Select>
```

Thank you for your help!!

**Comment by yesmeck** [comment]
@behind-design Could you provide a online demo using antd http://codepen.io/benjycui/pen/KgPZrE?editors=001 ?

**Comment by behind-design** [comment]
@yesmeck Yes I'll do it as soon as I can.
Nonetheless we've implemented a workaround for that issue, listening for keyboard events on the arrows when the element becomes focused.

Thank you for your help, I'll provide an example ASAP.

**Comment by benjycui** [comment]
ping @behind-design

**Comment by yesmeck** [comment]
Close since this issue is inactive.

**Comment by mkennedy3000** [comment]
@yesmeck Can this be reopened?

[Minimal Example](https://codepen.io/anon/pen/bKLwyY?editors=0010)

Experiencing the same issue using
* React@16.3.2 
* rc-select@8.0.2

**Comment by yesmeck** [comment]
@mkennedy3000 https://codesandbox.io/s/ryyvn9vnxq
