### ISSUE TITLE
IE 10/11 下 combobox 模式在 mount 时会触发 onInputChange 导致 下拉弹开

### ISSUE THREAD

**Issue by eternalsky** [react-component/select#151]
```jsx
<Select combobox defaultValue="杭州">
  <Option key="杭州">杭州</Option>
</Select>
```

最初以为是 placeholder 的原因，但是原来没有 placeholder，只要有 value 也会触发
react 版本是 0.14.8

**Comment by afc163** [comment]
试试 react@15

https://github.com/facebook/react/pull/5746

**Comment by eternalsky** [comment]
因为业务上还需要支持 IE8 的原因，目前还不具备条件切换到 react@15，请问是否还有其他解决方式？

**Comment by yesmeck** [comment]
试试用 `getInputElement` 自定义一个处理了 change 时间的 input 传给 Select?
