### ISSUE TITLE
如果Key和Value值是一样的情况，label不一样

### ISSUE THREAD

**Issue by crf444** [react-component/select#154]
我的版本是6.6.10，key和value不能同时生效，是否属于正常现象?

**Comment by yesmeck** [comment]
没看懂什么叫不能同时生效。

**Comment by crf444** [comment]
<Option key='aaa-a' value='bbb'>ccc</Option>
<Option key='aaa-b' value='bbb'>ccc</Option>

html原本是可以的，但是我用了value之后，这里有警告重复

**Comment by yesmeck** [comment]
你的代码是什么样的，你期望什么样的结果，实际是什么样的结果。

**Comment by crf444** [comment]
`const data = ['飞机', '火车', '地铁', '飞机'];`

`const renderOption = (type, idx) => {`
    return `<Option key={type + idx} value={type}>{type}</Option>;`
`};`

`const typeOptions = data.map(renderOption);`

因为我额外输了一个飞机的类型，一开始我加了value，导致选择的时候就报出了key重复的情况，于是我后来加了key，因为option里value值重复的情况也是存在的，但是key没有生效，所以是不是当value存在的时候，value就作为key，即使key存在.

**Comment by yesmeck** [comment]
`Option` 的 `key` 是没用的，`value` 会作为 `key`，`value` 不能重复。

**Comment by crf444** [comment]
Thank you!
