### ISSUE TITLE
Selected option's value is shown instead of it's name.

### ISSUE THREAD

**Issue by pastelsky** [react-component/select#155]
Consider this example:

```js
const options= [
  {value: 0, name: 'First'}, 
  {value: 1, name: 'Second'}, 
  {value: 2, name: 'Third' }
]

// render
<Select
  value={ 0 }
  onChange={ handleSelectionChange }
  placeholder="Select"
>
  {
    options
      .map(option => (
        <Select.Option key={ option.value } value={ option.value }>
          { option.name }
        </Select.Option>
       )
    )
  }
 </Select>
```

This should ideally render 

 ————
|     First  ˅ |
 ————

But it actually renders:
 ——
|     0       ˅ |
 ——

i.e. for some reason, it renders the value instead of the text inside `<Select.Option />`

**Comment by benjycui** [comment]
see: [`optionLabelProp`](https://github.com/react-component/select#api)

**Comment by afc163** [comment]
value is string.

**Comment by vince-fly** [comment]
u try it .
<Select
									animation='slide-up'
									placeholder="请选择国家"
									style={{width:320}}
									className ='currency-btn select-from-currency'
									choiceTransitionName="rc-select-selection__choice-zoom"
            			optionLabelProp="children"
									{...getFieldProps('cntryId',{
										validateFirst: true,
										rules: [{required:true,}],
										initialValue:''
									})}
									>{
										initData.countrys.map((item,index)=>(
											<Option key={index} value={item.id}>{item.localName}</Option>
										))
									}
								</Select>

**Comment by vince-fly** [comment]
`<Select
									animation='slide-up'
									placeholder="请选择国家"
									style={{width:320}}
									className ='currency-btn select-from-currency'
									choiceTransitionName="rc-select-selection__choice-zoom"
            			optionLabelProp="children"
									{...getFieldProps('cntryId',{
										validateFirst: true,
										rules: [{required:true,}],
										initialValue:''
									})}
									>{
										initData.countrys.map((item,index)=>(
											<Option key={index} value={item.id}>{item.localName}</Option>
										))
									}
								</Select>`

**Comment by yesmeck** [comment]
@pastelsky Try [`optionLabelProp`](https://github.com/react-component/select#api)
