### ISSUE TITLE
一个页面下多个 select， 有相同的 option 会导致 Child keys must be unique 错误

### ISSUE THREAD

**Issue by Darmody** [react-component/select#168]
![2017-03-07 15 13 19](https://cloud.githubusercontent.com/assets/6788752/23645773/b1b9f434-0348-11e7-8b15-5976b25d90ec.png)

我在一个页面下有两个 select, 并且 options 是一样的，因为 option 上的 key 都是 value，所以 react 报错了

**Comment by yesmeck** [comment]
https://ant.design/components/select/#components-select-demo-size

这个例子也是一个页面多个 Select 且有相同的 Option。

先检查下你每个 Select 下的 Option 吧。

**Comment by Darmody** [comment]
这是 `value` 和 `label` 相同的情况吧

当我 `label` 和 `value` 不同时，我在 option 上设置了 `value` 和 `key` 值，`key` 就不起作用了，就会用 `value` 来做 `key` 了

**Comment by yesmeck** [comment]
用 antd 重现一下 http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by Darmody** [comment]
哦我知道了，设置完 value 后还必须设置 key，保证唯一性。

我看文档一直以为 `key` 和 `value` 只能设置一个

**Comment by CallMeXYZ** [comment]
option values cannot duplicate even unique key was set : [see](https://codepen.io/CallMeXYZ/pen/zPxZeM)
