### ISSUE TITLE
Is there any plan to convert all code to use ES6 standard?

### ISSUE THREAD

**Issue by codTango** [react-component/select#169]
I'm just trying to add a little feature to the select, but what slows me down is the old way of react and all the `bind()` functions. I can understand that it's a pain to convert all source code to ES6 standard, but I'm still wondering if there's a plan to do so?

Also, since this project is on react@15+ now, should we remove the `React.createClass()` and `mixin`? As they're already deprecated.

**Comment by codTango** [comment]
@yiminghe so I'm thinking to sweep all the ES5 or old react to modern style, I probably will make a PR, is that OK?

**Comment by paranoidjk** [comment]
@codTanggo PR is welcome

**Comment by yiminghe** [comment]
it depends on mixin, if you can find a way to remove mixin properly, welcome pr

**Comment by damiangreen** [comment]
Part 1: https://github.com/react-component/select/pull/197

**Comment by damiangreen** [comment]
With regard to the mixin, I've taken a look at it, and it appears that as the mixin is only used in one file, there should be no problem to move all the functions into that class, i.e.e no need to create a higher order component. Are ther any thoughts on this? 
Does the original author know why a mixin was used originally?
