### ISSUE TITLE
当我选择一个select下面选项时，会不会触发dropdownmenu组件更新

### ISSUE THREAD

**Issue by percyi** [react-component/select#181]
我选择一个选项时，没有触发DropdownMenu组件的生命周期，这是正常现象吗？？

**Comment by yesmeck** [comment]
正常，DropdownMenu 不会 unmount。

**Comment by percyi** [comment]
那选择一个选项后，他的lastInputValue没有随着我的选择而改变啊，

**Comment by yesmeck** [comment]
说你碰到的具体的问题吧。

**Comment by percyi** [comment]
select有四个选项，第一个的value为空字符串，第一次展开下拉，选择一个选项。再一次展开下拉，选择一个其它选项，第三次展开下拉的时候，光标移到第一个选项位置（value为空字符串）

**Comment by percyi** [comment]
我用追踪代码后，发现是因为有段逻辑是lastInputValue ！= inputvalue时，把activekey置为了空

**Comment by yesmeck** [comment]
你是用 antd 吗？能不能给个 demo http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by percyi** [comment]
我发了图，到你的邮箱

**Comment by yesmeck** [comment]
没必要用空字符做 value，清空选项可以用 `allowClear`。

**Comment by percyi** [comment]
因为产品那边有这个需求，这个也是早就做出来的feature。空也是一个业务上的需求。方便做下更改吗？

**Comment by yesmeck** [comment]
来个 PR？
