### ISSUE TITLE
Support for pasting multiple options in the multiple mode

### ISSUE THREAD

**Issue by Alex1990** [react-component/select#191]
For example, I copy multiple options separated by newlines `\n` from somewhere, then I paste it into the input of select. This can improve the **efficiency of interaction**.

**Comment by yesmeck** [comment]
You can use  `tokenSeparators`.

**Comment by zachguo** [comment]
@yesmeck I'm using `antd v3.10.0`, it doesn't work. 
It seems `\n` was converted to ` `(space) before the input is broken into tokens.

**Comment by zachguo** [comment]
I will try to add a test case for this scenario and make a PR.

**Comment by zachguo** [comment]
@yesmeck Please try changing [this line in `tags` example](https://github.com/react-component/select/blob/master/examples/tags.js#L64) to `tokenSeparators={['\n','\r']}` and try any multiline input. Newlines would be converted to spaces, so tokenization fails.

I tried changing `,` to `\n` in [this test](https://github.com/react-component/select/blob/master/tests/Select.tags.spec.js#L61-L98), but it cannot capture the error. So newlines are probably lost before `input`'s `change` event is triggered.

**Comment by zachguo** [comment]
The default `<input/>` component causes the problem.
I tried changing `input` to `textarea`, then it's correctly working, but the style was messed up.
Is it possible to let `rc-select` use `textarea` instead of `input`?
