### ISSUE TITLE
Unique key prop

### ISSUE THREAD

**Issue by brysgo** [react-component/select#192]
The `key` prop is expected to be unique in a list of react elements, maybe we could namespace this prop internally and provide react with a sequential key prop that would satisfy this requirement?

**Comment by paranoidjk** [comment]
what's your problem? Does rc-select have any key warning?

**Comment by brysgo** [comment]
Yes

**Comment by paranoidjk** [comment]
so, a reproducible demo please

**Comment by yesmeck** [comment]
Closed no response.
