### ISSUE TITLE
Show action on focus

### ISSUE THREAD

**Issue by vuxor** [react-component/select#194]
By default Select component will show dropdown list and set focus in search field (if showSearch prop is true) when you click on it or when you press "arrow down key" on keyboard when component is focused. What I want is to do all of this when I focus on component using tab. I found that if I manually edit showAction prop to be equal ['click', 'focus'] this will work. But I can't pass down showAction prop, because [this line](https://github.com/react-component/select/blob/master/src/SelectTrigger.jsx#L123) will override it.
Is there any other way I can do this, or will you allow showAction to be changed in props?

**Comment by paranoidjk** [comment]
maybe we can add a showAction props to rc-select，which default is ['click'], and   showAction={disabled ? [] : [this
.props.showAction']
