### ISSUE TITLE
Additional attributes on MenuItem's <li> - such as option's value

### ISSUE THREAD

**Issue by ntgn81** [react-component/select#196]
Right now, the `<li>` rendered for each Option/OptGroup has fixed number of attributes.

For our automated tests, we would like to add extra attributes onto the `<li>` so our automation software can find select options by value instead of by display text.

Would it be a good idea to add a new property to Select.Option/OptGroup - `optionElementAttributes` that gets passed on to `MenuItem` to be rendered?

Something like this on https://github.com/react-component/select/blob/master/src/FilterMixin.js#L87

```js
      sel = sel.concat(value.map((singleValue) => {
        const key = singleValue.key;
        return (<MenuItem
          style={UNSELECTABLE_STYLE}
          attribute={...UNSELECTABLE_ATTRIBUTE, ... singleValue.optionElementAttributes}
          value={key}
          key={key}
        >
          {key}
        </MenuItem>);
      }));

**Comment by yesmeck** [comment]
Hello @ntgn81, for now you can pass `className` to `Option`:

```javascript
<Option className="jack" value="jack">Jack</Option>
```

renders:

```html
<li unselectable="unselectable" class="rc-select-dropdown-menu-item jack" role="menuitem" aria-selected="false" style="user-select: none;">Jack</li>
```
