### ISSUE TITLE
Option to put the key (value) inside the input instead of label

### ISSUE THREAD

**Issue by zachary822** [react-component/select#205]
https://github.com/react-component/select/blob/master/src/Select.jsx#L278

Instead of putting label as the `inputValue`, have an option to show `value` directly instead.

**Comment by yesmeck** [comment]
The link is outdated, could you explain your request more detailed?

**Comment by zachary822** [comment]
Wow. This is so long ago. I remember circumventing this problem entirely, and I'm a little bit fuzzy on what it was about in the first place.
