### ISSUE TITLE
componentWillUpdate中为什么直接this.state = state?

### ISSUE THREAD

**Issue by tofdragon** [react-component/select#206]
componentWillUpdate(nextProps, nextState) {
    this.props = nextProps;
    this.state = nextState;
    this.adjustOpenState();
  },

react官方代码是不建议直接给this.state设置对象的，而是this.setState()，此处这样做的目的是？
而且代码中还有直接this.state.xxx =xxx；
// why not use setState?
this.state.inputValue = this.getInputDOMNode().value = '';

**Comment by paranoidjk** [comment]
componentWillUpdate 里面不允许 setState: https://facebook.github.io/react/docs/react-component.html#componentwillupdate

@yiminghe https://github.com/react-component/select/blob/master/src/Select.jsx#L118 `adjustOpenState`  不能放到`componentWillReceiveProps` 里面做吗，是什么原因需要在 `componentWillUpdate` 里面修改 state ？




@tofdragon 你的第二个问题我没看到，哪行代码？请发链接

**Comment by tofdragon** [comment]
@paranoidjk  componentWillUpdate(nextProps, nextState) {
    this.props = nextProps;
    this.state = nextState;
    this.adjustOpenState();
  }   

this.state  = nextState

**Comment by yesmeck** [comment]
是为了在 `adjustOpenState` 里拿到的 `this.state` 是 `nextState`。
