### ISSUE TITLE
提供focus()方法

### ISSUE THREAD

**Issue by demonfchan** [react-component/select#207]
希望提供focus()方法，方便使用代码去控制焦点
看Select.jsx中的实现发现，可以通过this.refs.select.refs.selection.focus()来控制获得焦点，可不可以在Select组件中增加
```javascript
focus(){
  this.refs.selection.focus();
}
```
来让外界可以直接this.refs.select.focus()来调用

**Comment by yesmeck** [comment]
欢迎 PR。
