### ISSUE TITLE
showSearch状态下选中某个选项, 会触发一次onSearch事件, 且此时的Value为空

### ISSUE THREAD

**Issue by Gavinchen92** [react-component/select#219]
showSearch状态下选中某个选项, 会触发一次onSearch事件, 且此时的Value为空

**Comment by yesmeck** [comment]
预期的行为 https://github.com/react-component/select/issues/100

**Comment by Gavinchen92** [comment]
@yesmeck 有没有办法可以不触发

**Comment by Pysics** [comment]
本来写了一大段想吐槽，突然意识到忽略空的检索关键字`value.trim()`可以解决

**Comment by areyouse7en** [comment]
这问题有解决吗
