### ISSUE TITLE
Customize <Option> component

### ISSUE THREAD

**Issue by dmmarmol** [react-component/select#225]
I'm using Ant.Design `<Select />` and `<Option />` component and I'd need to extend and customize the native `<Option />` to introduce a button at the top right of the component. My simplest and dumb Idea was to do something like

```js
const CustomOption = (props) => (
    <Option value={props.value} key={props.value}>
        {props.label}
        <Button />
    </Option>
));
```

And then
```js
<Select>
    <CustomOption />
    ...
</Select>
```
But this aint working at all. Anyone has an idea if its possible to customize the Option component?

**Comment by yesmeck** [comment]
A alternative way:
```javascript
const customOption = (props) => (
    <Option value={props.value} key={props.value}>
        {props.label}
        <Button />
    </Option>
));
```

```javascript
<Select>
    {customOption()}
</Select>
```

**Comment by dmmarmol** [comment]
I'd be useful if the `<Select.Option />` component could be extended through a `<Select />` prop like `renderOption` or something like that. However, your suggestion did the trick so thanks a lot @yesmeck!

**Comment by yesmeck** [comment]
Close since it's not possible to implement passing custom component to `Select` in current architecture.
