### ISSUE TITLE
想要一个不渲染MenuItemGroup的title的选项

### ISSUE THREAD

**Issue by muzea** [react-component/select#231]
https://github.com/react-component/select/blob/5eae3629fff3532834007745d7b54de3ac6dc8e2/src/Select.jsx#L878

有时候仅仅是想要一个缩进的效果，但是一旦提供了key就会有一个label显示在上面，想要一个不渲染label的选项

**Comment by yesmeck** [comment]
你说的缩进效果是指什么？

**Comment by muzea** [comment]
类似这种
https://codesandbox.io/s/5703w9pnn

**Comment by yutingzhao1991** [comment]
如果你只是想要缩进那么 `<Option value="jack"><span style={{paddingLeft: 10}}>Jack</span></Option>` 这样就可以了。 https://codesandbox.io/s/6zl24l2j3k

**Comment by muzea** [comment]
=。= 不知道当时为啥不加padding，大概是智障了吧
