### ISSUE TITLE
Capability to open multi-select upon tabbing to component and keyDown = Enter

### ISSUE THREAD

**Issue by ambz4lyfe** [react-component/select#235]
This logic exists for single/combobox selects, would be helpful for multiselects when there are an abundance of form input controls.

**Comment by yesmeck** [comment]
If I understand you correctly, you can set `showAction={['focus']}` after https://github.com/react-component/select/commit/7283d9bcea3a36acef61586a47198908576c35cf is released.

**Comment by ambz4lyfe** [comment]
Great, when do you expect to release it?

**Comment by yesmeck** [comment]
Released in `rc-select@7.0.0`.
