### ISSUE TITLE
Ability to view select input text in the options 

### ISSUE THREAD

**Issue by ambz4lyfe** [react-component/select#237]
It would be great if we could highlight the text found in the options (either in the form of bold text or some custom styling). Would you be open to this change? I've attached a screenshot of what the change could potentially look like.

https://github.com/ambz4lyfe/select/blob/master/feature-enhancements/select-visual-indicator.jpg

**Comment by yesmeck** [comment]
I's like to leave it to user side. Here is a example https://codesandbox.io/s/2p4jpm4jz0
