### ISSUE TITLE
Select 中遍历 `this.props.children` 的方式是错误的

### ISSUE THREAD

**Issue by chengjianhua** [react-component/select#241]
Trace:

https://github.com/react-component/select/blob/1f40efd13a3aa2584723e26eb4603c37cb61b264/src/Select.jsx#L815

https://github.com/react-component/select/blob/1f40efd13a3aa2584723e26eb4603c37cb61b264/src/util.js#L46

发现这个问题的代码如下:

```
<Select>
  <Option>An extra option</Option>
  {levelOptions}
</Select>
```

以上代码会抛出一个这样的错误:

![image](https://user-images.githubusercontent.com/10795207/32359936-73113032-c01f-11e7-8ad4-0282c1ed6679.png)

----

其实之前报的是另外一个错误, 后来莫名的不能复现了, `utils.js` 中的 `getValuePropValue` 抛出异常:

https://github.com/react-component/select/blob/1f40efd13a3aa2584723e26eb4603c37cb61b264/src/util.js#L5

大意是不能从 `undefined` 中读取 `value` 这个值.

----

其实一看代码就觉得不对劲了, 为什么会用 `toArray` 这个方法来遍历 children, react 中的 `children` 不是一个完全的数组, 至少和你期望的数组形式有那么一点区别.

为了辨别出 `toArray` 不能遍历 `props.children` 因此导致出错的原因, 我做了一个实验:

```
export default function LogChildren({
  children
}) {
  console.log(children);

  return null;
}
```

```
          <LogChildren>
            <Option>haha</Option>
            {[
              <Option key="all" value={PT_LEVEL_ALL}>不限 Level</Option>,
              <Option key="level-none" value={PT_LEVEL_NONE}>没有 Level</Option>,
              ...LEVELS.map(level => (
                <Option key={level} value={level}>Level {level}</Option>
              )),
            ]}
          </LogChildren>
```

`console.log(children)` 输出的结果如下:

![image](https://user-images.githubusercontent.com/10795207/32360067-8c0dd364-c020-11e7-97c8-019cb55a93cb.png)

----

如果我使用 `React.Children` 来遍历的话呢 ?

```
import React from 'react';

export default function LogChildren({
  children
}) {
  const childrenArray = [];

  React.Children.forEach(children, (child) => {
    childrenArray.push(child);
  });

  console.group('React.Children');
  console.log(childrenArray);
  console.groupEnd('React.Children');

  return null;
}
```

![image](https://user-images.githubusercontent.com/10795207/32360163-3f9af47a-c021-11e7-8c0e-21ee9dacf91d.png)

结果是这样的, `React.Children.forEach` 会为我们抹平一个 Element Array 和 Single Element 混合情况下的遍历的差异, 这正是 `toArray` 不能做到的.

-----

前面 bug 的原因就是因为数组嵌了数组, 嵌套数组没有展开. 显然当一个数组元素是 `[]` 的时候, 你并不能从中获取到 `props` 属性, 自然 `value in props` 会出错.

希望你们能修正这个问题, 使用标准的 React API 来完成.

谢谢 ~

> BTW, 如果你们觉得可行的话, 我很乐意在周末的时间提个 PR.

**Comment by yesmeck** [comment]
这里其实应该用这个 [toArrat](https://github.com/react-component/util/blob/master/src/Children/toArray.js)，欢迎 PR。

**Comment by chengjianhua** [comment]
@yesmeck 我跑测试的时候很多测试都是挂的, 你们跑的时候也是这样的嘛 😅

**Comment by yesmeck** [comment]
你看 CI 是好的

**Comment by chengjianhua** [comment]
@yesmeck 就是这样觉得很奇怪, 你们本地跑的时候会这样么 ?

**Comment by chengjianhua** [comment]
看懂了, 原来 travis 上跑的是 lint ..

**Comment by yesmeck** [comment]
确保依赖都是最新的，还有错的话贴上来看看

**Comment by chengjianhua** [comment]
@yesmeck 

👌 用 lint 的话是没问题的, 不过我想问下为什么写了这么多的测试却没有使用啊, 我看有 11 个测试失败了, 我看了下测试代码, 是测试写错了 ... 之后 PR 里给你 review 吧.

我把测试修复怎么样, 修复之后我改代码也就更放心了, 现在不写测试的话还真的不太放心改代码 🙄

**Comment by yesmeck** [comment]
测试也没问题的 https://travis-ci.org/react-component/select/jobs/296147209

**Comment by afc163** [comment]
<img width="700" alt="image" src="https://user-images.githubusercontent.com/507615/32382445-30cd13a4-c0f0-11e7-97c1-80be4f74f93c.png">

**Comment by chengjianhua** [comment]
@afc163 我试了几遍 `rm -rf node_modules && yarn && yarn run test`, 结果都是上方的结果 ..

**Comment by yesmeck** [comment]
可能是 node 版本的问题，用最新的。

**Comment by chengjianhua** [comment]
先找你们确认下, 你们本地是没问题的么 ? 我使用了最新的 `v9.0.0`, 我看 travis 上使用的也是这个版本.

![image](https://user-images.githubusercontent.com/10795207/32402156-b8afd0e0-c0eb-11e7-9f6f-3f0a60664a1a.png)

我看那些错误的代码逻辑确实是有问题的 ... 不管怎么样, 我先试试 CI 上是什么结果. 我还是想确认下你们本地的情况.

**Comment by yesmeck** [comment]
确实也报错了，我看下。

**Comment by yesmeck** [comment]
好了，用了 jest beta 版的原因。拉下 master 重新装下依赖。
