### ISSUE TITLE
Case sensitive search , it should be incasesensitive

### ISSUE THREAD

**Issue by diljithvandanam** [react-component/select#244]

**Comment by yesmeck** [comment]
You can use `filterOption` prop to create a  `<CaseIsensitiveSelect />`.

**Comment by diljithvandanam** [comment]
Hi , can you give me an example for <CaseIsensitiveSelect />

**Comment by diljithvandanam** [comment]
CaseIsensitiveSelect

**Comment by yesmeck** [comment]
```javasciprt
const caseIsensitiveFilter = (input, option) => 
    option.children.toLowerCase().indexOf(input.toLowerCase()) > -1;

const CaseIsensitiveSelect = (props) => <Select {...props} />
```

**Comment by diljithvandanam** [comment]
Hi , the following is my code 

caseinsensitivesearch(option,input){
let options =  option.filter((item)=>{
    return //condition
  });
  return options;
}


<Select
showSearch={true}
filterOption = {this.caseinsensitivesearch.bind(this,this.state.opt)}>
  <OptGroup >
        <Option >....</Option>
  </OptGroup>
  .
  .
  .
</Select>
