### ISSUE TITLE
Should multiple-select layer display the Option children text?

### ISSUE THREAD

**Issue by marswong** [react-component/select#245]
IMO, it is better to display children text in the multiple-select layer, cause there may be no relation between the children text and the Option's `key`/`value`, here is the sample:

```javascript
/* eslint no-console: 0 */

import React from 'react';
import Select, { Option } from 'rc-select';
import 'rc-select/assets/index.less';
import ReactDOM from 'react-dom';

function MultipleSelect() {
  const cases = {
    0: { name: 'Case 1' },
    1: { name: 'Case 2' },
  };
  const caseKeys = ['0', '1'];

  return (
    <Select style={{ width: 500 }} multiple allowClear>
      {
        caseKeys.map(key => (
          <Option key={key} value={key}>{cases[key].name}</Option>
        ))
      }
    </Select>
  );
}

ReactDOM.render(<MultipleSelect />, document.getElementById('__react-content'));
```

just modify the [multiple example](http://react-component.github.io/select/examples/multiple.html) to see the effects:

![image](https://user-images.githubusercontent.com/10388933/32718747-0c38d9e6-c899-11e7-9a9b-4ea18f18819f.png)

It may be better to render children text in the selected layer, but now it's just bound to the Option's `key`/`value`, so that user cannot customize the display.

**Comment by yesmeck** [comment]
`optionLabelProp="children"`

**Comment by marswong** [comment]
it works, thank you :)
