### ISSUE TITLE
need a check for `maxTagPlaceholder`, as it might be a function rather than string

### ISSUE THREAD

**Issue by codTango** [react-component/select#247]
I have opened a PR [#243](https://github.com/react-component/select/pull/243), as suggested by @yesmeck, I am able to pass `maxTagPlaceholder` which is a function that will return the element that has tooltip, but now if I hover on the "+N...." pillow, it will display [Object Object] as tooltip. I think we need to add a check on `maxTagPlaceholder`since it could be a function in such case. Also if we could control whether to show a tooltip would be nice. In my case, we don't want to make this pillow disabled.

<img width="440" alt="screen shot 2017-11-17 at 5 28 22 pm" src="https://user-images.githubusercontent.com/5359697/32971775-d0040a82-cbbc-11e7-9c12-318e0c05b201.png">

**Comment by yesmeck** [comment]
Release in rc-select@7.3.0

**Comment by yesmeck** [comment]
`maxTagPlaceholder` can be a function now, and it accepts omitted values as parameter.
