### ISSUE TITLE
IE 11 Bug

### ISSUE THREAD

**Issue by pshox** [react-component/select#248]
Hi guys,

i found a bug in internet explorer only 11 version.
when you click on scrollbar -  dropdown will immediately dissapear, i tried to play around with this but unfortunatelly doesnt find solution to fix it.

**Comment by yesmeck** [comment]
Can you reproduce it on http://react-component.github.io/select/?

**Comment by pshox** [comment]
yes

**Comment by yesmeck** [comment]
Weird, I can not reproduce it. Can you provide more info?

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/7934

**Comment by pshox** [comment]
yea, it happens absolutely like here
https://user-images.githubusercontent.com/8079497/32414180-4bbf570c-c286-11e7-9b9e-97042f86a593.gif

**Comment by pshox** [comment]
any updates with this issue ?

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design/issues/7934#issuecomment-346134766 @pshox Are you using windows 10?

**Comment by pshox** [comment]
@yesmeck yes

**Comment by yesmeck** [comment]
Could you help us debugging it? I can not find a windows 10 installed ie11 now.

**Comment by doarrison** [comment]
I can confirm that this happens on ie11 on my windows 10 machine (IE Version 11.125.16299.0). Perhaps it is because IE calls blur event when selecting scrollbar as mentioned here:

https://stackoverflow.com/questions/2023779/clicking-on-a-divs-scroll-bar-fires-the-blur-event-in-i-e

**Comment by tianlang89757** [comment]
@pshox @afc163 @doarrison @yesmeck This problem I have solved, the solution is to delete antd.css stylesheet inside .ant-select-dropdown-menu under the overflow: auto style, you can solve the IE11 browser Edge document mode drag the scroll bar selection box Disappear problem
