### ISSUE TITLE
如何支持标签为一个复杂对象（node）而不是简单string和number的情况

### ISSUE THREAD

**Issue by Jason121250148** [react-component/select#249]
目标效果如图
![image](https://user-images.githubusercontent.com/10795499/33106868-67d52192-cf6f-11e7-8907-c71162813395.png)
目前实现这种效果会报错：
![image](https://user-images.githubusercontent.com/10795499/33106894-856af7fe-cf6f-11e7-9cef-b32bfdce5fd3.png)
Option代码如下：
![image](https://user-images.githubusercontent.com/10795499/33106915-a0a49dae-cf6f-11e7-825b-df492f8510c2.png)
Select代码如下：
![image](https://user-images.githubusercontent.com/10795499/33106929-aff51ed2-cf6f-11e7-84c1-6ba929471783.png)
求助，不知是否是没正确使用还是就是不支持node对象

**Comment by Jason121250148** [comment]
@yesmeck

**Comment by yesmeck** [comment]
现在就支持的。另外那个警告已经说的很明白了。

**Comment by Jason121250148** [comment]
value值为
![image](https://user-images.githubusercontent.com/10795499/33107150-e01b39d8-cf70-11e7-8294-b67e2d011420.png)
onChange方法直接返回的就是这个值，label就是对象，应该怎么改呢，不太明白。。

**Comment by yesmeck** [comment]
嗯，这是个问题，我改以下。

**Comment by yesmeck** [comment]
修正了 7.3.1

**Comment by Jason121250148** [comment]
OK
