### ISSUE TITLE
Disabled options are preemptively filtered out before the custom filter

### ISSUE THREAD

**Issue by dan-diaz** [react-component/select#251]
from src/Select.jsx:
```
filterOption = (input, child, defaultFilter = defaultFilterFn) => {
    const { value } = this.state;
    const lastValue = value[value.length - 1];
    if (!input || (lastValue && lastValue.backfill)) {
      return true;
    }
    let filterFn = this.props.filterOption;
    if ('filterOption' in this.props) {
      if (this.props.filterOption === true) {
        filterFn = defaultFilter;
      }
    } else {
      filterFn = defaultFilter;
    }

    if (!filterFn) {
      return true;
    } else if (child.props.disabled) {
      return false;
    } else if (typeof filterFn === 'function') {
      return filterFn.call(this, input, child);
    }
    return true;
  };
```

I want to pass in a custom filter option that will still return `true` for options that are disabled.
That is not possible as this will return `false` on a disabled option before the custom filter is reached.

We can change the order of operations to let a custom filter decide what to do with disabled options, but this breaks the existing test cases and may really screw with existing custom filters for other users. I almost submitted a PR, but this stopped me in my tracks.

That being said, I think the choice to allow disabled options should be in the hands of the developer if they decide to override the default filter.

**Comment by yesmeck** [comment]
I changed the order in 7.4.0.

**Comment by dan-diaz** [comment]
@yesmeck wonderful! thank you!
