### ISSUE TITLE
Dropdown does not scroll with Select within <div>

### ISSUE THREAD

**Issue by gschwa** [react-component/select#253]
When the `Select` lives within a scrollable div, the dropdown does not scroll with the Select box. Here is an example that illustrates the issue:  https://codesandbox.io/s/j2q9omnly9

You will notice that it works fine when the body scrolls but not an inner div. I tried changing the container using `getPopupContainer` but to no avail.

**Comment by yesmeck** [comment]
https://codesandbox.io/s/q32mmlwx26

You need set `position: 'relative'` on the container, because dropdown has a absolute position.

**Comment by yesmeck** [comment]
You can set a proper heigh to the dropdown menu.

```javascript
 <Select dropdownMenuStyle={{ height: 200 }}>
```

**Comment by gschwa** [comment]
Our application has many selects in many different modals so tweaking the height per modal is not an option. Is there no way to force a recalculation on the positioning on scroll?

**Comment by ulrichb** [comment]
> Is there no way to force a recalculation on the positioning on scroll?

@gschwa Same here. My drop-down popups are clipped when opened/contained in small scrollable divs. Did you find any solution?
