### ISSUE TITLE
Adjusting the position offset of the dropdown?

### ISSUE THREAD

**Issue by gschwa** [react-component/select#254]
The current dropdown is positioned approximately 5px below the dropdown. Is it possible to adjust the placement to close the gap?

**Comment by yutingzhao1991** [comment]
Can you tell me more details about why you want this?

**Comment by yesmeck** [comment]
We do has have a prop  called `dropdownAlign` for popup position tweaking, it's value is a [dom-align](https://github.com/yiminghe/dom-align) object.

And here is [default positions](https://github.com/react-component/select/blob/dade915d81069b8d3b3b5679bb9daee7e992faba/src/SelectTrigger.jsx#L11-L28).

**Comment by yutingzhao1991** [comment]
@yesmeck why `dropdownAlign` not in the doc. Not recommended usage?

**Comment by yesmeck** [comment]
It's a little complex to explain this props and change popup position is not accord with Ant Design specification, so we did not describe this prop in the antd's docs.
