### ISSUE TITLE
Assign name attribute to the input element

### ISSUE THREAD

**Issue by steelow** [react-component/select#256]
Is there a way to assign name attribute to the input element stored within the rc-select component? I would like to submit selected values as part of my form.

Thanks

**Comment by yutingzhao1991** [comment]
We can't, rc-select do not built with `<input>`, just `<div>`. `name` attribute not works.

You can ues https://github.com/react-component/form component.

**Comment by steelow** [comment]
What does the getInputElement prop do. It says to customize input. Could it be a way to add input element to the rc-select component? There does not seem to be any in-depth documentation to the component.

**Comment by yutingzhao1991** [comment]
@steelow getInputElement just for searchable select. You can find it at: https://github.com/react-component/select/blob/master/src/Select.jsx#L1068.

For temporary you can wrap rc-select to a new component with a input:

```
<div>
  <input name="xxx"/>
  <RCSelect/>
</input>
```

In the future, Maybe we can and a hidden input inside rc-select for this situation.
