### ISSUE TITLE
Support any type value in single and multiple mode

### ISSUE THREAD

**Issue by yesmeck** [react-component/select#257]

**Comment by rdvojmoc** [comment]
What is status on this issue?

**Comment by yesmeck** [comment]
I've tried it and realized that it's not a good idea to pass object to option. #157 is a better solution to pass objects. I will revisit #157 when I found a better implementation for #157.

**Comment by rdvojmoc** [comment]
What is best solution at the moment in case we need complex object to be selected on Select component?
Select in my case is used in Form together with `getFieldDecorator`.

**Comment by yesmeck** [comment]
Keep the complex object list to a variable, then find the object when submit form.
