### ISSUE TITLE
maxTagCount of 0 should not display 

### ISSUE THREAD

**Issue by jweir13** [react-component/select#258]
Setting maxTagCount to 0 displays all selected tags (the same as not specifying maxTagCount). 

maxTagCount = 0 should be a valid option.

If maxTagCount = 0 and one or more options have been selected, can the maxTagPlaceholder be displayed and no tags shown?

**Comment by yutingzhao1991** [comment]
> If maxTagCount = 0 and one or more options have been selected, can the maxTagPlaceholder be displayed and no tags shown?

agree with this.

@jweir13 welcome to make a PR!~

**Comment by grunmin** [comment]
@yutingzhao1991 
I created a PR #259

**Comment by yutingzhao1991** [comment]
fix in 7.6.0
