### ISSUE TITLE
whether to update inputValue when updating the  selected option

### ISSUE THREAD

**Issue by kanweiwei** [react-component/select#269]
related [https://github.com/ant-design/ant-design/issues/9445](https://github.com/ant-design/ant-design/issues/9445);

`optionLabelProp="children"`
Should update inputValue when updating the children of selected option

如果选择时，以Option的children来填充输入框。目前的代码在componentWillReceiveProps里，考虑了用户手动指定当前选中的条目的情况。如果某一刻，option的value没有发生变化，children发生变化了，输入框的值是否应该更新？

**Comment by yesmeck** [comment]
在 ant-design/ant-design#9445 讨论吧。
