### ISSUE TITLE
Feature request: pass down the original event to the onChange handler

### ISSUE THREAD

**Issue by mgcrea** [react-component/select#274]
Coming from [react-toolbox](https://github.com/react-toolbox/react-toolbox), one pattern I really liked to use is to rely on the `name` prop of the control to easily know inside the handler from which control it has been called. Just like what we can do with the [HTML name prop](https://developer.mozilla.org/fr/docs/Web/HTML/Element/Select).

It enables complex forms to have a single `onInputChange` handler that is really clean and efficient:

```
  handleInputChange = (value, ev) => {
    this.setState({[ev.target.name]: value});
  }
```

However it requires the original `event.target` to get back the HTML name prop. Usually passed as the last argument to the onChange handler;

Do you think the event could be passed as a third argument to allow such workflow in a non-breaking way?

I will gladly provide a PR with unit test if you agree on the changes.

**Comment by yesmeck** [comment]
We already pass Option as the second argument to `onChange`.
