### ISSUE TITLE
当 align 为 topLeft 的情况下，如果配置 onSearch 时，有可能会有样式出错的情况。

### ISSUE THREAD

**Issue by eternalsky** [react-component/select#279]
![2018-03-26 8 44 35](https://user-images.githubusercontent.com/8038928/37907409-9b591ba2-3137-11e8-94d2-1d3f2d038d90.png)

onSearch 时候，因为模糊匹配或者过滤，选项由多变少，会导致 dropdown 的部分会离 trigger 区域很远。

**Comment by eternalsky** [comment]
目前想到的办法之一，可能是在 Item 数量发生变化，而且是 topLeft 的情况下，重新触发一次 align

**Comment by afc163** [comment]
same as https://github.com/ant-design/ant-design/issues/9784

**Comment by eternalsky** [comment]
请问有修复的策略吗~ 需要 pr 吗~

**Comment by yesmeck** [comment]
@zombieJ 在看了？

**Comment by zombieJ** [comment]
这几个都是update时没有重新计算align，我来搞。

**Comment by eternalsky** [comment]
@zombieJ 请问这个问题的进展如何？

**Comment by zombieJ** [comment]
ref: https://github.com/react-component/select/commit/34b459a2036e730fbb9e02e7bf8f3a1533c64419
