### ISSUE TITLE
7.7.6版本，当option过多时，键盘keyup和keydown无法使得滚动条滚动

### ISSUE THREAD

**Issue by xwzpp** [react-component/select#283]
在7.7.6版本中，过多option的时候，当使用键盘keyup和keydown无法使得滚动条滚动，排查发现可能是依赖了最新的rc-menu@6.2.7存在问题，测试将其换成rc-menu@6.2.6，该bug消失。能否帮忙看看，谢谢。

**Comment by yesmeck** [comment]
https://github.com/react-component/menu/issues/126
