### ISSUE TITLE
Options value prop should accept boolean type

### ISSUE THREAD

**Issue by reyronald** [react-component/select#285]
https://github.com/react-component/select/blob/e863267673b9108c0a6f17213e8f1a2ce4cfbb3d/src/Option.jsx#L4-L10

Right now, the Options value prop only accepts `string`s and `number`s. Is there a particular reason why it couldn't accept `bool` type as well? 

If it doesn't break any existing functionality and could be added and willing to submit a PR.

**Comment by yesmeck** [comment]
Use `radio`, if you want to use boolean value.

**Comment by yesmeck** [comment]
It's not only about `proptype`, we will do string operation on the option value

https://github.com/react-component/select/blob/e863267673b9108c0a6f17213e8f1a2ce4cfbb3d/src/util.js#L152

As a workaround, you can add any prop to `Option`:

```javascript
<Option boolValue={false}>

function hangeChange(value, option) {
  console.log(option.prop.boolValue);
}
```

**Comment by reyronald** [comment]
I see!

I guess you took into account for those string operations to work even if the Option has a `number` value, since that is accepted as a prop type as well. If you ever revisit that code and have some time, perhaps those considerations could apply without much effort to booleans too.

Anyway,  your suggestion is a valid workaround, I'll be using that, thank you! And also thank you for open sourcing this great component library, the team have done  a wonderful job and it's been very useful to the community!
