### ISSUE TITLE
Allow to customise Option or set a style attribute

### ISSUE THREAD

**Issue by ditiem** [react-component/select#310]
I am doing a font-select and I would like each select-option to be rendered with the font-family option. In short:

```
<Select>
  { fonts.map( font =>
   <Option style={{ fontFamily: font.family }}>{{ font.name }}</Option> }
</Select>
```

Neither style prop is accepted nor children can be some Element.  For the latter case I am looking for something like this:

```
<Select>
  { fonts.map( font =>
   <Option><span style={{ fontFamily: font.family }}>{{ font.name }}</span></Option> }
</Select>
```

**Comment by yutingzhao1991** [comment]
Option's children can be a element. http://react-component.github.io/select/examples/single.html

**Comment by ditiem** [comment]
Apologies. You are right!

optionLabelProp="value" is what I was missing (the children was selected and the Input showed [Object object]).

Thank you a lot!
