### ISSUE TITLE
combobox 的一点小疑问

### ISSUE THREAD

**Issue by eternalsky** [react-component/select#32]
https://github.com/react-component/select/blob/master/src/Select.jsx#L98

在 props 有 value 的情况下，combobox 的展示值 inputValue 就等于 value[0]，那么可否像 multiple 一样可以对应 label 呢~ 毕竟选出来的值一般还是看 label 的

**Comment by yiminghe** [comment]
欢迎 pr

**Comment by sundyxfan** [comment]
@yiminghe  @eternalsky  上面那个问题解决了吗

**Comment by yiminghe** [comment]
combobox 不能显示 label 的，

**Comment by sundyxfan** [comment]
@yiminghe  combobox选择后还是显示label比较合理吧
