### ISSUE TITLE
Styling the select component

### ISSUE THREAD

**Issue by Marina-R** [react-component/select#322]
Hi! I'm having issues with re-writing default select component styles from 'rc-select/assets/index.css'; Seems like I can set width of it, but can set height, and other properties. 
![screen shot 2018-09-11 at 5 38 15 pm](https://user-images.githubusercontent.com/11147660/45367266-864cfd00-b5e9-11e8-9bc5-05e640c10363.png)

How can I overwrite all default styles from 'rc-select/assets/index.css'?
Thanks!

**Comment by zombieJ** [comment]
You can use chrome dev tool to track the element and adjust : )

**Comment by ddemolina** [comment]
Hi!
I'd like to understand your solution. You mean I have to use a selector using library classNames?

Could be a better option that API library has a prop like selectionClassName which apply to that div. 
There is a prop called dropdownClassName using the same techniche

Thanks!

**Comment by zombieJ** [comment]
hi @ddemolina , 
Currently we try to avoid provider too much prop as `xxxClassName` and wish user use `prefixCls` for style tracking since `xxxClassName` is not easy to memory.

You can ref [Ant Design](https://ant.design) for using the `prefixCls` customize style.

**Comment by ddemolina** [comment]
Ah, ok. I think I understand your solution. This way I can write my own rules avoiding to reset some of the library rules. The trade off is prefixCls apply to all the css library classes.

This implies I have to copy all css rules from the library to my css file and I have to consider css classes names like an API contract and I have to check if something related to css change when update the library.

This is the idea?

**Comment by zombieJ** [comment]
hi @ddemolina,
Thanks for your reply. `prefixCls` is used for customize full style of component. But if you only want to change part of then. You can set `className` at top instead. The `prefixCls` will keep `rc-select` as default.
