### ISSUE TITLE
something wrong of the style of checkbox 

### ISSUE THREAD

**Issue by m26597** [react-component/select#323]
I've realized a full check by the using of a checkbox.But sometimes it will look a little different like :

                 
![default](https://user-images.githubusercontent.com/39291213/45398448-c0b0ab80-b676-11e8-855f-703b9705c5de.png)

I don't know How it works .

SOS!

**Comment by m26597** [comment]
the normal state is :
       
![default](https://user-images.githubusercontent.com/39291213/45398683-ad521000-b677-11e8-8181-2c9e48f5e025.png)

**Comment by m26597** [comment]
And it looks different from the demo in the offical website. I think it may be the version of antd, so I tried to update the version of my antd. Should I only change the version at the package.json or need I to build the antd again?

**Comment by zombieJ** [comment]
This is not `rc-select` issue.
I guess it's affected by your customize css, pls check it with chrome dev tool.
If you find it is common bug, pls fire issue to https://github.com/ant-design/ant-design/issues
