### ISSUE TITLE
版本 8.6.5 报错

### ISSUE THREAD

**Issue by nuintun** [react-component/select#359]
更新到 8.6.5 后控制台出现警告，8.6.4 无警告！

![_20181219093540](https://user-images.githubusercontent.com/1730277/50193439-9a836180-0371-11e9-9e17-28e0a278e8a7.png)

**Comment by yoyo837** [comment]
同

**Comment by kravets-levko** [comment]
Bug is at these lines: 
https://github.com/react-component/select/blob/master/src/PropTypes.ts#L103
https://github.com/react-component/select/blob/master/src/PropTypes.ts#L123
Probably should be something like this:
```javascript
PropTypes.checkPropTypes({ [propName]: validate }, props, 'prop', componentName);
```

**Comment by nanxiaobei** [comment]
`Warning: Failed value type: The value `isRequired` is marked as required in `Select`, but its value is `undefined`.`

升级到 Ant Design 3.11.2 发现这个报错，追溯到了这里，
看报错信息大概也能看出来，很明显是参数传错了...
