### ISSUE TITLE
combobox 模式时，默认高亮第一个

### ISSUE THREAD

**Issue by afc163** [react-component/select#38]
演示：http://react-component.github.io/select/examples/suggest.html
版本：5.4.0
重现步骤：输入『w』，弹出搜索建议框，删除『w』后再次输入『r』，第一个选项未默认高亮。希望可以实现默认高亮功能。

**Comment by yiminghe** [comment]
高亮了啊

**Comment by afc163** [comment]
试试『就』『他』，好像不是很稳定。

**Comment by afc163** [comment]
看了下这种搜索提示的交互，一般有两种：

1. 类似 https://www.alitrip.com/ 的城市输入，会有默认选中的行为，可直接回车选择。
2. 还有 http://www.baidu.com 和 google 的搜索框自动完成，默认不选中。

是不是加一个 `selectFirstOnInput` 的选项，类似这个：http://docs.spmjs.io/arale-autocomplete/latest/examples/#%E9%BB%98%E8%AE%A4%E9%80%89%E4%B8%AD%E7%AC%AC%E4%B8%80%E4%B8%AA

**Comment by yiminghe** [comment]
defaultActiveFirst

**Comment by afc163** [comment]
:+1:
