### ISSUE TITLE
Can't run test on Windows

### ISSUE THREAD

**Issue by zy410419243** [react-component/select#385]
1. When I run `npm test`, it throws an error as below,

    `Jest cli not found! Please reinstall or fire a issue fot this.`

2. CI test not working, is it normal?

**Comment by ztplz** [comment]
重装下依赖试试    mac能跑

**Comment by zy410419243** [comment]
下过很多遍，不光 test 跑不起，start 也跑不起

1. test 看不出为啥会少 cli

2. 然后 start， 看上去 storybook 生成配置的路径不对。

/node_modules/rc-tools/storybook/config.js，这里面 require 的路径是这样的

`require('D:\github\select\storybook/index.js');`

报的错是这样的

`Module not found: Error: Can't resolve 'D:githubselectstorybook/index.js' in 'D:\github\select\node_modules\_rc-tools@9.3.8@rc-tools\lib\storybook'`

也就是这个反斜杠在 window 下被当成转义符，然后路径就错了

**Comment by zy410419243** [comment]
好吧，都找到这了，我等会来个 pr ...

**Comment by zy410419243** [comment]
然后啊，我本地 start 是能跑起来了，只是

![9wo1j_3 pi 0w4 tj a](https://user-images.githubusercontent.com/24520193/53299850-df001180-387a-11e9-81e8-318828f51b7d.png)

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/53299888-57ff6900-387b-11e9-862d-6293c69045ba.png)
win 是向前的  跟uninx类的路径不同

**Comment by fung-yu** [comment]
> 好吧，都找到这了，我等会来个 pr ...

为什么我拷贝进去就给我冲了，代码不生效呢！

**Comment by zy410419243** [comment]
年久失修了，有缘再改吧。
