### ISSUE TITLE
需支持自定义 render 到 Option 和 Selected.

### ISSUE THREAD

**Issue by TossShinHwa** [react-component/select#39]
实际场景大概是这样的:

![image](https://cloud.githubusercontent.com/assets/3007674/11863798/01dd6fa8-a4d2-11e5-90b9-8ce4ad2c82d7.png)

**Comment by benjycui** [comment]
如果只是希望增加个图标，在 `Option` 内用 `img` 就行了。

```jsx
<Option value="china"><img src="url" />China</Option>
```

**Comment by TossShinHwa** [comment]
Cool, 原来能直接支持 HTML. 因为示例里面没看到. 那选择了之后在选中项也和 Option 的内容一致吗? 如果我希望不一致呢? 比如上面场景中, 我可能不需要国家代号.

类似这样.

![image](https://cloud.githubusercontent.com/assets/3007674/11865883/0c878744-a4e2-11e5-9633-800907543a8f.png)

**Comment by benjycui** [comment]
像下面这样就可以动态更新 `Option` 内的字符串了。

```jsx
<Option value="china"><img src="url" />{variable}</Option>
```

然后这属于 React 的范畴，你可以找下相关的资料。

**Comment by TossShinHwa** [comment]
不好意思, 我没有说清楚.

我是指选中时, 在 Input 中的文本, 和 Option 中的内容是不一样的. 因为可能我 Option 内容是非常复杂的. 可以参考下 [Typeahead](https://twitter.github.io/typeahead.js/) 首页的 example, 不过这个是下拉菜单.

**Comment by benjycui** [comment]
日前的逻辑应该是不支持的。。。就不知道是否考虑支持 Typeahead 这种风格的 Select @yiminghe

**Comment by yiminghe** [comment]
try optionLabelProp
