### ISSUE TITLE
select popup 随着页面滚动时的位置问题

### ISSUE THREAD

**Issue by Luncher** [react-component/select#404]
如果 `select` 处于可滚动的父容器里面的时候，会出现位置问题，这个时候可以设置 `getPopupContainer` 来解决。为什么不在 `select` 组件外面包一个容器把 `position` 设置为 `relative`呢？如：

```tsx
<div className="select-container" style={{ positon: 'relative'}} ref={this.wrapper} />
  <Select getPopupContainer={() => this.wrapper.current} />
</div>
```

这样 `select` 的 `popup` 就不会出现位置问题了。

**Comment by Luncher** [comment]
我想知道为什么要把这个职责抛给用户，而不是 `antd` 直接实现了。谢谢!

**Comment by Luncher** [comment]
@nighca

**Comment by nighca** [comment]
@Luncher 似乎这个 repo 平时维护的人不怎么看 issue...这个行为的根源应该是在 [`rc-trigger`](https://github.com/react-component/trigger)，不过那个 repo 的 issue 也基本没人处理了。

我去简单看了下其他流行的 UI lib 的做法（[materail-ui](https://material-ui.com/components/selects/#selects)/[react-bootstrap](https://react-bootstrap.github.io/components/dropdowns/)/[semantic-ui](https://react.semantic-ui.com/addons/select/)/[grommet](https://v2.grommet.io/select)），还真没有默认 body + `getPopupContainer` props 的做法的，大部分是你上边提到的做法（挨着 trigger target 放），也有放 body 不过自己监听滚动事件自动调整的（[grommet](https://v2.grommet.io/select)）

这么看的话 `getPopupContainer` 的做法应该没有太多特别的考虑，我们可以自己包一层处理。或者也可以再去 antd 的主 repo 提 issue 或者在 [gitter](https://gitter.im/ant-design/ant-design) 提出来看看

**Comment by afc163** [comment]
默认放 body 是因为应用中任何一级 div 上的 `overflow: hidden` 都可能影响浮层的展现，放在 body 下能避免大多数此类问题。

```
<div>
  <div style={{ overflow: 'hidden' }}>
    <div>
      <div>
         <Select getPopupContainer={() => this.wrapper.current} />
      </div>
    </div>
  </div>
</div>
```

**Comment by Luncher** [comment]
@nighca 你说的那个唯一情况出现了..

**Comment by Luncher** [comment]
> 默认放 body 是因为中后台应用中任何一级 div 上的 `overflow: hidden` 都可能影响浮层的展现（大型项目中经常遇到，通常还不是你自己加的），放在 body 下能避免大多数此类问题。
> 
> ```
> <div>
>   <div style={{ overflow: 'hidden' }}>
>     <div>
>       <div>
>          <Select getPopupContainer={() => this.wrapper.current} />
>       </div>
>     </div>
>   </div>
> </div>
> ```

我们再实际使用过程中，确实比较少遇到你说的这种情况，更多的时候都是自己要去包装一下..

**Comment by afc163** [comment]
这是一个抉择，默认选哪个都会有很多答疑。在我们这里的已有应用中开，overflow 滥用是满严重的。

**Comment by nighca** [comment]
@afc163 你说的 overflow 的情况我们讨论的时候也考虑过，不过 overflow 的滥用很大的原因在于基于 `overflow: hidden` 的清除浮动手段的滥用，我觉得现代的应用中这样的情况应该会越来越少

**Comment by afc163** [comment]
我们需要考虑现实情况的，不只是 `overflow: hidden`，还有很多 `overflow: auto` 的滥用。
