### ISSUE TITLE
Get the selected value from React

### ISSUE THREAD

**Issue by lucasreal** [react-component/select#41]
Hi, how can i get the selected value(s) from the React component?

**Comment by benjycui** [comment]
`onChange`

Read the documentation before you ask, please.

**Comment by lucasreal** [comment]
I meant to get the selected values beside events moments.

for instance I have the Select component dynamically called from inside another component, how can I get the value just from the React Component of the Select?

and please, don't close a thread that I didn't said that is ok, this is unethical.

Thanks!

**Comment by benjycui** [comment]
I knew what you want to do. This is not about rc-select, but React's principle. 

> Remember: React is all about one-way data flow down the component hierarchy. --[Thinking in React](https://facebook.github.io/react/docs/thinking-in-react.html)

So, please get Select's value by `onChange` like [React's example](https://facebook.github.io/react/docs/thinking-in-react.html#step-5-add-inverse-data-flow).

BTW, are you OK? :-)
