### ISSUE TITLE
删除 onSelect / onDeselect  

### ISSUE THREAD

**Issue by warmhug** [react-component/select#42]
tree-select 中确定只有 onChange 监听整个所有的变化；onSearch 监听输入框的变化。

select 组件也 删除掉 onSelect / onDeselect  ，会有什么问题？

**Comment by afc163** [comment]
select 的 onSelect / onDeselect 在 antd 里应该没用到，应该没问题。

**Comment by yiminghe** [comment]
不能删的，combobox 的 onChange 和 onSelect 不是一回事

**Comment by warmhug** [comment]
http://react-component.github.io/select/examples/combobox.html  例子里也是用 onChange

**Comment by afc163** [comment]
其实 combobox 的 onSelect 自动完成那一下也会触发 onChange 。因为最终都是关注输入框的变化。

**Comment by warmhug** [comment]
纠结这个是因为：tree-select  要跟 select 这块一致。如果把 select 当成 input 之类的，只关注变化值，只有一个值。没想到其他有什么漏洞？

**Comment by yiminghe** [comment]
onSelect 特指从提示选的 onChange 可能是随意输的
