### ISSUE TITLE
为什么使用绝对定位而不是相对定位来添加 DOM.

### ISSUE THREAD

**Issue by TossShinHwa** [react-component/select#44]
发现一个问题, 当点击出下拉菜单后, 这个菜单 DOM 时直接 append 到 body 中, 并且计算了一个绝对定位来搞定位置问题的. 

那么问题来了, 如果我本来就是一个绝对定位的 box, 在里面要使用 Select 的话就会变得比较麻烦. 每次移动都要去计算它对于 body 来说的绝对定位位置. (因为实际上这个 box 是没有移动的, 比较典型的场景是 Modal)

在 [rc-calendar](https://github.com/react-component/calendar) 中暴露了一个 align 参数使用 [dom-align](http://yiminghe.me/dom-align/) 用来解决这个问题, 这个配置相当繁琐(需要配合 DOM id). 而且在 rc-select 也没有提供相应的接口. 那如果遇到这个情况应该如何处理呢? 像上面说的不停的手动计算吗?

所以, 为什么 rc-select 以及 rc-calendar 不直接把内容 append 到 触发的input DOM 的后面呢? 这样只需要相对于父元素定位就可以了, 因为 input 和 rc-xxx 的父元素相同, 定位是相当方便的.

谢谢.

**Comment by benjycui** [comment]
Relative: https://github.com/react-component/calendar/issues/95

**Comment by benjycui** [comment]
> 所以, 为什么 rc-select 以及 rc-calendar 不直接把内容 append 到 触发的input DOM 的后面呢? 这样只需要相对于父元素定位就可以了, 因为 input 和 rc-xxx 的父元素相同, 定位是相当方便的.

append 到 trigger 后面也不是完美的方案，see: https://www.qianduan.net/that-thing-on-the-z-index/

要保证在任何情况下弹层都在最前面，append 到 body 会比较容易实现。。。

@yiminghe

**Comment by TossShinHwa** [comment]
@benjycui 是的, 确实各有优劣. 但是出现我上面所说的情况时, 该怎么解决定位问题呢? 有最佳实践之类的吗?

**Comment by yiminghe** [comment]
会和 rc-calendar 一样增加 align 配置，大多数场景添加到 body 不容易出错
