### ISSUE TITLE
storybook 预览代码不能拖动

### ISSUE THREAD

**Issue by zxf4399** [react-component/select#440]
https://select.react-component.now.sh/?path=/story/rc-select--mul-suggest

**Comment by zxf4399** [comment]
@sorrycc

**Comment by SarahLyu** [comment]
把<pre>overflow改成scroll就行了

**Comment by SarahLyu** [comment]
把\<pre\>的overflow改成scroll就行了

**Comment by zxf4399** [comment]
@SarahLyu father打包封装之后的storybook出现的问题，我是在自己利用father打包之后发现的，但是没人管，自己也不能加样式代码吧
