### ISSUE TITLE
Bad export.

### ISSUE THREAD

**Issue by MartynasZilinskas** [react-component/select#45]
The way export now is a bad example. 
Instead of this:
```js
import Select from './Select';
import Option from './Option';
import OptGroup from './OptGroup';
Select.Option = Option;
Select.OptGroup = OptGroup;
export default Select;
```
Should be like this:
```js
import Select from './Select';
import Option from './Option';
import OptGroup from './OptGroup';
export { Select, Option, OptGroup}
```

With bad export, it makes impossible to use your module correctly in Typescript language.

**Comment by benjycui** [comment]
It's JavaScript's convention, see: https://github.com/facebook/react/blob/master/src/React.js

You should find solution in TypeScript community.

**Comment by xujihui1985** [comment]
@MartynasZilinskas what is the version of typescript you are using? I thought after v1.7, typescript has great compatibility with es6, it should work

**Comment by MartynasZilinskas** [comment]
Are you sure it's the right way? Because the way it's exported. You add like dictionary on `Select` while it is an JSX.Element. If it was another language it would be impossible to do it.

**Comment by DovydasNavickas** [comment]
@benjycui, are you referring to this part of the file? :smile: 
```
React.__SECRET_DOM_DO_NOT_USE_OR_YOU_WILL_BE_FIRED = ReactDOM;
React.__SECRET_DOM_SERVER_DO_NOT_USE_OR_YOU_WILL_BE_FIRED = ReactDOMServer;
```

Because that is not really a convention, more of a hack for backwards-compatibility used by React team. They will remove it in next major version.

@MartynasZilinskas, could you make PR with how should that be done properly? :clap:

**Comment by MartynasZilinskas** [comment]
Here is pull request: https://github.com/react-component/select/pull/47
And it will not break current import syntax.

**Comment by yiminghe** [comment]
This will break commonjs style(which this project was using before), but this pr is good for ES import.
So I will accept and bump minor version.

**Comment by benjycui** [comment]
@DovydasNavickas I mean that adding properties to JS object dynamically. It is the only way to export things before ES6.

```jsx
module.exports.greeting = 'Hello world!';
```

Anyway, it is always a good idea to follow the latest standard.

**Comment by benjycui** [comment]
@yiminghe shall we export all the componets in ES6 way?

**Comment by yiminghe** [comment]
Yes, better to follow the latest standard.

**Comment by benjycui** [comment]
@react-component/admin FYI :b
