### ISSUE TITLE
Select on mobile trigger focus after blur event was fired

### ISSUE THREAD

**Issue by MichelKansou** [react-component/select#521]
I'm using the Select component with onSelect to trigger blur event, on desktop the component is working correctly but on mobile the Select component is still on focus.

Here's an example of my project code 
```
  const selectRef = useRef(null);

  const onSelect = () => {
    selectRef.current.blur();
  };


return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        height: 'calc(100vh - 16px)',
      }}
    >
      <div style={{ display: 'flex', justifyContent: 'center' }}>
        <div>
          <Select
            onChange={onChange}
            onFocus={onFocus}
            onBlur={onBlur}
            onSelect={onSelect}
            ref={selectRef}
            dropdownMatchSelectWidth={500}
            value={selectedValue}
          >
            <Option value="1">Jack Jack Jack Jack Jack Jack Jack Jack Jack Jack Jack</Option>
            <Option value="2">Lucy Lucy Lucy Lucy Lucy Lucy Lucy Lucy Lucy Lucy</Option>
            <Option value="3">Jill</Option>
          </Select>
        </div>
      </div>
    </div>
  );
```

I looked at the Select component code it use `generateSelector` in `src/generate.tsx`, and I found that in `onInternalMouseDown` function there's a condition that trigger another focus event on the component it's working properly in desktop but in mobile popupElement contains always the active element menu
```
if (!popupElement.contains(document.activeElement)) {
    selectorRef.current.focus();
}
```

Is it possible to add mobile check to avoid the focus for this condition ?

**Comment by conioX** [comment]
for this issue i have problem on mobile browser android chrome, i cannot clicks anything when dropdown select open? any news?

**Comment by chillyistkult** [comment]
Looks like this can also happen on desktop, but I am not sure under which conditions. Had several users so far, who managed to trigger this error.

<img width="831" alt="Bildschirmfoto 2021-02-04 um 16 23 30" src="https://user-images.githubusercontent.com/1689047/106914566-7035bf00-6705-11eb-81bb-c3cbdf488260.png">

**Comment by afc163** [comment]
PR is welcome~

**Comment by krouw** [comment]
Same issue here on mobile views!

Browser: Firefox 84.0.2
OS: Mac OS 10.14.6
rc-select version: 12.0.4

> TypeError: selectorRef.current is null
>Call Stack
>onInternalMouseDown/timeoutId<
>node_modules/rc-select/es/generate.js (673:0)
