### ISSUE TITLE
对于搜索内容的疑问

### ISSUE THREAD

**Issue by NinoFocus** [react-component/select#53]
为什么搜索匹配的是Option的value，而不是展示出来的文字？

`<Option value="1">测试一</Option>`

我在搜索框中输入“测试”，搜索不到内容，输入“1”，能搜到“测试一”

**Comment by yiminghe** [comment]
optionFilterProp

**Comment by NinoFocus** [comment]
已解决，谢谢

**Comment by afc163** [comment]
解决的话，麻烦关闭 issue ~
