### ISSUE TITLE
Options that are dynamically changed don't clear the search value

### ISSUE THREAD

**Issue by itap006** [react-component/select#547]
I am generating a different options list based on another select fields. Whenever the options change, the search field doesnst clear the old value

Here is a codepen to try it out. [codepen](https://codesandbox.io/s/sparkling-fog-p77ke?file=/src/App.js)

**Comment by svpease** [comment]
As you are controlling the <Select /> component with the "value" prop, you needed to update the state correctly so that state.second becomes undefined. 

See changed CodePen sandbox here: https://codesandbox.io/s/fast-smoke-biscr?file=/src/App.js

**Comment by itap006** [comment]
Thank you for your response. It makes sense now.
