### ISSUE TITLE
after choosing a value there is a bug with styles

### ISSUE THREAD

**Issue by plandem** [react-component/select#55]
styles changes after selection.

here is before selection:
https://www.dropbox.com/s/p7jgte1ml01f7ea/Screenshot%202016-02-17%2011.55.19.png?dl=0
https://www.dropbox.com/s/zozxao96mbeq9du/Screenshot%202016-02-17%2011.57.44.png?dl=0

and it's after selection:
https://www.dropbox.com/s/0uwb1axgtjld79i/Screenshot%202016-02-17%2011.56.41.png?dl=0
https://www.dropbox.com/s/pm9dzx4siw7gcy6/Screenshot%202016-02-17%2011.57.22.png?dl=0

**Comment by plandem** [comment]
sorry, looks like it was my fault. set option: 'dropdownMatchSelectWidth' to false

**Comment by yiminghe** [comment]
you can also try to set `style` prop
