### ISSUE TITLE
rc-select的历史版本(tag)里没有9.2.3

### ISSUE THREAD

**Issue by FranklyCai** [react-component/select#551]
rc-select的历史版本(tag)里没有9.2.3，但是9.2.3是跟antd3.26.18配套的，并且在https://developer.aliyun.com/mirror/npm/package/rc-select的历史列表里可以看到9.2.3在8个月前更新，排在10.0.0-rc.4和10.0.0-rc.5之间，希望能补上，谢谢了

**Comment by yoyo837** [comment]
试一下npm 淘宝镜像的同步链接，触发一下看看？我这边也是用3.x 的最后版本没有你说说的问题

**Comment by yoyo837** [comment]
你说的是git的tag？

**Comment by yoyo837** [comment]
就是https://github.com/react-component/select/tree/9.x，你这边还需要打tag不？

**Comment by yoyo837** [comment]
已创建
