### ISSUE TITLE
支持 select 分组

### ISSUE THREAD

**Issue by afc163** [react-component/select#6]
类似原生的 `<optgroup></optgroup>`。

http://select2.github.io/examples.html#templating

**Comment by yiminghe** [comment]
@warmhug 这个 feature 做下，提 pr 讨论下

**Comment by warmhug** [comment]
确定即将支持

**Comment by afc163** [comment]
@warmhug 在 http://ant.design/components/select/ 里加一下分组的功能吧。

**Comment by warmhug** [comment]
done
