### ISSUE TITLE
Filter null child

### ISSUE THREAD

**Issue by yesmeck** [react-component/select#63]
If  children include a null `child`,  this [line](https://github.com/react-component/select/blob/master/src%2FFilterMixin.js#L31)  will raise error.

Consider following situation, if  `showJack` is null, rc-select should filter the null child.

```javascript
<Select defaultValue="lucy" style={{ width: 120 }}>
  { showJack && <Option value="jack">Jack</Option> }
  <Option value="lucy">Lucy</Option>
</Select>
```

**Comment by yiminghe** [comment]
use array variable
