### ISSUE TITLE
How to get rid of the gap between dropdown and select menu?

### ISSUE THREAD

**Issue by zdila** [react-component/select#64]
Hello. Thanks for the awesome component!

Please how to get rid of the gap between dropdown and select menu? The dropdown is positioned absolutely so I can't do `.rc-select-dropdown { position: relative; top: -2px }`.

**Comment by yiminghe** [comment]
6.0.0-beta.2

dropdownAlign={{ offset:[0,0] }}

**Comment by zdila** [comment]
Thanks!
