### ISSUE TITLE
Add support to remove selected className if another option is active

### ISSUE THREAD

**Issue by zdila** [react-component/select#65]
Please add support to remove `.rc-select-dropdown-menu-item-selected` from the selected item if another item has `.rc-select-dropdown-menu-item-active`.

The reason is that I would like the select dropdown to behave as in native `<select>` where only a single item of a dropdown is highlighted at a time.

**Comment by yiminghe** [comment]
### chrome select/option on mac

 selected  option has a check mark on the left edge, active option has a blur background

**Comment by zdila** [comment]
I see. So I would like it to behave like https://jqueryui.com/selectmenu/.

**Comment by yiminghe** [comment]
It will need some change in rc-menu, which i think it is not worth it.

you can try to pr on rc-menu
