### ISSUE TITLE
version 13.0.0-alpha.2 can't build in next.js

### ISSUE THREAD

**Issue by i-ked-ii** [react-component/select#652]
version 13.0.0-alpha.2 can't build in next.js

I try to install and build again. It's not working then I use old version "rc-select": "~12.1.6" in package.json

<img width="564" alt="Screen Shot 2564-08-18 at 11 58 03" src="https://user-images.githubusercontent.com/23306577/129839668-4d6ac37d-5ee2-4d1b-b99c-6dd18e442a47.png">

**Comment by yuuk** [comment]
拉下来的文件里面就没有js文件

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/select/releases/tag/v13.0.0-alpha.3
