### ISSUE TITLE
Add extra class to select to distinguish the dropdown placement if dropdown menu is open

### ISSUE THREAD

**Issue by zdila** [react-component/select#66]
Opened dropdown menu has currently a class like `rc-select-dropdown-placement-bottomLeft`. We need similar class for the select itself.

In our design the dropdown is attached to select and we want to remove the rounded corners on both select and dropdown on the side they touch. For this we must also know which direction did the dropdown open.

**Comment by yiminghe** [comment]
can you try to make a pr, thanks
