### ISSUE TITLE
不再支持 require 的使用方式了吗？

### ISSUE THREAD

**Issue by eternalsky** [react-component/select#75]
Select.jsx 里面还是有加 module.exports = exports['default'] 的，应该是有在用 add-module-exports ，但 index 的 export 方式会导致 add-module-exports 失效。

```
export { Option, OptGroup };
export default Select;
```
但这样不会

```
export.Option = Option;
export.OptGroup = OptGroup;
export default Select
```

**Comment by benjycui** [comment]
请使用最新版 https://github.com/react-component/select/blob/master/src/index.js
