### ISSUE TITLE
不再支持 require 的使用方式了吗？

### ISSUE THREAD

**Issue by eternalsky** [react-component/select#76]
https://github.com/react-component/select/issues/75 的问题并没有解决

问题不是出在 没有挂变量，而是多于一个 export 时，add-module-exports 是没有效果，这导致 lib/index.js 里最后是没有那句 module.exports = export['default'].

**Comment by benjycui** [comment]
本地测试表示没问题：

![image](https://cloud.githubusercontent.com/assets/3580607/14634283/dcc4bd1e-0653-11e6-854f-bf1128d2777e.png)

所以你应该向 add-module-exports 提 issue?

**Comment by yiminghe** [comment]
嗯，请使用 import (服务器端也请使用 import)
