### ISSUE TITLE
Select component breaks on searching unavailable data and using arrow key to select "not found" and pressing enter key

### ISSUE THREAD

**Issue by mushycode** [react-component/select#77]
Search for a value not in the drop down list. The notFoundContent "not found" shows up in the drop down, which is disabled and can not be clicked by the mouse. But the component breaks if we press down arrow followed by enter key. The case is possibly not handled. The example in the site also is broken.

**Comment by yiminghe** [comment]
thanks.

https://github.com/react-component/menu/commit/473a039fb03524c5558e6df379f6d0048bfae885
