### ISSUE TITLE
是否可以支持multiple选择的最大数目

### ISSUE THREAD

**Issue by liangqing** [react-component/select#85]
增加一个选项，如果多选的时候超过该选项设置的数目就不可以再选择了。

**Comment by benjycui** [comment]
这个需求用表单校验去保证可好？https://github.com/react-component/form

没有提示，直接让用户选择不了的话，用户会感到困惑的。

**Comment by liangqing** [comment]
但是我这边的情况是用户每次选择都需要作响应的，所以如果可以随便选的话会导致联动的部分体验不是很好。另外表单验证的help貌似只能是换一行？下拉选择菜单会遮住它。
提示可以在控件后面加一句话就行了。

**Comment by benjycui** [comment]
校验不通过，就不更新联动部分，`help={null}` 覆盖默认的 `help`，然后在控件后面自已加个 提示？

See: http://ant.design/components/form/#demo-validate-basic

**Comment by benjycui** [comment]
![image](https://cloud.githubusercontent.com/assets/3580607/15103276/f4269198-15db-11e6-87df-31428e8d4b0b.png)

**Comment by liangqing** [comment]
表单验证这个我也试过的，就是用户反应很奇怪，明明只能选择3个，为什么选了3个后，那个多项选择单还不关闭？必须要点一下页面其他地方才能关闭？

这个功能的目的是在提示用户最多能选多少个的情况下，用户选了最多个数后，不应该让它还能够选的，否则会让人困惑。
而且，用户误选超出数目的选项后，之后还要点击删除，是一种时间浪费。

此外，校验不通过，就不更新联动部分，这个都需要额外写一些代码去处理，如果有这个功能，就可以简化这些。

**Comment by benjycui** [comment]
> 表单验证这个我也试过的，就是用户反应很奇怪，明明只能选择3个，为什么选了3个后，那个多项选择单还不关闭？必须要点一下页面其他地方才能关闭？

@yiminghe 现在 rc-select 的下拉菜单显示与否好像不是受控的？

> 而且，用户误选超出数目的选项后，之后还要点击删除，是一种时间浪费。

`value` 是受控的，可以代码控制不超过 3 个选项。

> 此外，校验不通过，就不更新联动部分，这个都需要额外写一些代码去处理，如果有这个功能，就可以简化这些。

其实你只不过是把业务代码挪进组件里面了而已。

**Comment by yiminghe** [comment]
下拉菜单显示不是受控，逻辑比较多

**Comment by kylezhang** [comment]
@benjycui 
> **value 是受控的，可以代码控制不超过 3 个选项。**
怎么在我的页面中控制选择的options不超过3个？

**Comment by yiminghe** [comment]
http://react-component.github.io/select/examples/force-suggest.html
