### ISSUE TITLE
可以暴露出 onScroll 类似的接口嘛？

### ISSUE THREAD

**Issue by ystarlongzi** [react-component/select#90]
因为数据实在是太多了，想在滚动的时候，再加载数据进来。

或者支持[infiniteScroll](https://github.com/react-component/select/issues/18)

**Comment by yiminghe** [comment]
欢迎 pr 下，不清楚怎么集成 @warmhug

**Comment by warmhug** [comment]
如果加到组件里、成本略大、而且又会增加很多API。建议 dropdown 、 select 这些都支持一个脱离 menu 的能完全自定义的弹出框内容，然后响应用户的 `onCustomSelected` 之类事件，让用户自己去找类似 react-infinite 之类的优秀第三方库加进来实现这个功能。还有其他一些组件、如 table 列 filter 框等、实际业务中都遇到有完全自定义的需求，现在都没支持的很好

**Comment by yesmeck** [comment]
https://github.com/react-component/select/pull/195

**Comment by xuoutput** [comment]
有 demo 么? @yesmeck @afc163
