### ISSUE TITLE
Attempted import error: 'useComposeRef' is not  exported from 'rc-util/es/ref'.

### ISSUE THREAD

**Issue by wify-techteam** [react-component/select#938]
package.json of "rc-select"

`{
  "name": "rc-select",
  "version": "14.0.0",
  "description": "React Select",
  "engines": {
    "node": ">=8.x"
  },
  "keywords": [
    "react",
    "react-component",
    "react-select",
    "select"
  ],
  "main": "./lib/index",
  "module": "./es/index",
  "types": "./lib/index.d.ts",
  "files": [
    "assets/*.css",
    "assets/*.less",
    "es",
    "lib"
  ],
  "homepage": "http://github.com/react-component/select",
  "repository": {
    "type": "git",
    "url": "git@github.com:react-component/select.git"
  },
  "bugs": {
    "url": "http://github.com/react-component/select/issues"
  },
  "license": "MIT",
  "scripts": {
    "start": "dumi dev",
    "build": "dumi build",
    "compile": "father build",
    "prepublishOnly": "npm run compile && np --yolo --no-publish",
    "lint": "eslint src/ docs/examples/ --ext .tsx,.ts,.jsx,.js",
    "test": "father test",
    "tsc": "tsc --noEmit",
    "now-build": "npm run build"
  },
  "peerDependencies": {
    "react": "*",
    "react-dom": "*"
  },
  "dependencies": {
    "@babel/runtime": "^7.10.1",
    "classnames": "2.x",
    "rc-motion": "^2.0.1",
    "rc-overflow": "^1.0.0",
    "rc-trigger": "^5.0.4",
    "rc-util": "^5.16.1",
    "rc-virtual-list": "^3.2.0"
  },
  "devDependencies": {
    "@types/enzyme": "^3.10.9",
    "@types/jest": "^26.0.24",
    "@types/react": "^17.0.15",
    "@types/react-dom": "^17.0.3",
    "cross-env": "^7.0.0",
    "dumi": "^1.1.32",
    "enzyme": "^3.3.0",
    "enzyme-to-json": "^3.4.0",
    "eslint": "^7.1.0",
    "father": "^2.13.2",
    "jsonp": "^0.2.1",
    "np": "^7.5.0",
    "rc-dialog": "^8.1.1",
    "typescript": "^4.2.3"
  }
}
`

**Comment by afc163** [comment]
Need reproduce.

**Comment by wify-techteam** [comment]
I am not able reproduce it now, i deleted the node modules and switched by node version to 16.14.0 and it worked well.
I was not using this package directly instead was using "antd" which internally utilized this repo.

Thanks a lot for your help and prompt response
