### ISSUE TITLE
New aria-label attribute broke Playwright tests

### ISSUE THREAD

**Issue by yfrommelt** [react-component/select#973]
Since this commit https://github.com/react-component/select/commit/b2d241fc6a7fcea66bd2b744f017c7d3c5e75881, all playwright test can no longer focus select by label. All select on my form have the exact same label now. There is an alternative way to do the same selection as before. Or there is a way to customize the value of aria-label ? 
I'm using antd@5.8.2 atm.

**Comment by afc163** [comment]
Could you provide a reproduce test case?

**Comment by yfrommelt** [comment]
I've done a simple test repo https://github.com/yfrommelt/rc-select-tests.
[First commit](https://github.com/yfrommelt/rc-select-tests/actions/runs/5818848164) with the last version of `rc-select` example test fail to reach select with label. 
[Second commit](https://github.com/yfrommelt/rc-select-tests/actions/runs/5818895811) with a downgrade to `rc-select@14.7.3` tests run smoothly.

**Comment by pierluigigiancola** [comment]
Upgrading to antd5 also broke some of my test since the label get overwritten by 'Search'

**Comment by pierluigigiancola** [comment]
@afc163 thanks 😄
