### ISSUE TITLE
单选时，在 value undefined 或者 null 的情况下，隐藏 clear 的 icon

### ISSUE THREAD

**Issue by eternalsky** [react-component/select#99]
icon 在那里也没什么用处，隐藏起来会更美观一些，待 value 有值时再显示。

**Comment by yiminghe** [comment]
http://react-component.github.io/select/examples/single.html 是隐藏的

**Comment by eternalsky** [comment]
ok~ 是新版本的特性吗~我升级下看看

**Comment by afc163** [comment]
有效的。
